# Generated by Django 2.0.7 on 2020-10-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201011_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_texture',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='wall_texture',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
